// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using SrmCapita.CoreServices.Data;

namespace SrmCapita.CoreServices.Migrations
{
    [DbContext(typeof(ClientesDbContext))]
    [Migration("20190111163447_Initial")]
    partial class Initial
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "2.1.4-rtm-31024");

            modelBuilder.Entity("SrmCapita.CoreServices.Model.Cliente", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnName("ID");

                    b.Property<DateTime>("DataCadastro")
                        .HasColumnName("Data")
                        .HasColumnType("datetime");

                    b.Property<string>("Email")
                        .HasColumnName("Email")
                        .HasMaxLength(255)
                        .IsUnicode(false);

                    b.Property<decimal>("LimiteCompra")
                        .HasColumnName("Limite")
                        .HasColumnType("decimal");

                    b.Property<string>("Nome")
                        .HasColumnName("Nome")
                        .HasMaxLength(255)
                        .IsUnicode(false);

                    b.Property<string>("Telefone")
                        .HasColumnName("Fone")
                        .HasMaxLength(255)
                        .IsUnicode(false);

                    b.HasKey("Id");

                    b.ToTable("Clientes");
                });
#pragma warning restore 612, 618
        }
    }
}
